# Generated by Django 6.1.1 on 2026-09-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('date_created_gmt', models.DateTimeField(blank=True, null=True)),
                ('date_modified_gmt', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('on-hold', 'En espera'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('date_paid_gmt', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-date_paid_gmt'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('date_created_gmt', models.DateTimeField(blank=True, null=True)),
                ('date_modified_gmt', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('parent_woo_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('success', 'Completada'), ('error', 'Error')], default='running', max_length=10)),
                ('trigger', models.CharField(choices=[('initial', 'Inicial completa'), ('incremental', 'Incremental'), ('manual', 'Manual')], default='incremental', max_length=15)),
                ('categories_synced', models.PositiveIntegerField(default=0)),
                ('products_synced', models.PositiveIntegerField(default=0)),
                ('variations_synced', models.PositiveIntegerField(default=0)),
                ('orders_synced', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Registro de sincronización',
                'verbose_name_plural': 'Registros de sincronización',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('product_woo_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('variation_woo_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('date_created_gmt', models.DateTimeField(blank=True, null=True)),
                ('date_modified_gmt', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('publish', 'Publicado'), ('draft', 'Borrador'), ('pending', 'Pendiente'), ('private', 'Privado')], default='publish', max_length=20)),
                ('product_type', models.CharField(default='simple', max_length=20)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('stock_status', models.CharField(blank=True, default='', max_length=20)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('permalink', models.URLField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='core.productcategory')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-date_created_gmt'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('date_created_gmt', models.DateTimeField(blank=True, null=True)),
                ('date_modified_gmt', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('stock_status', models.CharField(blank=True, default='', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='core.product')),
            ],
            options={
                'verbose_name': 'Variación',
                'verbose_name_plural': 'Variaciones',
                'unique_together': {('product', 'woo_id')},
            },
        ),
    ]
